<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReferenceController;
use Illuminate\Support\Facades\Route;

// Landing: send people to their library. Guests get bounced to login by the
// auth middleware on the target route.
Route::get('/', fn () => redirect()->route('references.index'));

Route::middleware('auth')->group(function () {
    // Reference library
    Route::get('/references', [ReferenceController::class, 'index'])->name('references.index');
    Route::get('/references/create', [ReferenceController::class, 'create'])->name('references.create');
    Route::post('/references', [ReferenceController::class, 'store'])->name('references.store');

    // Literal routes MUST come before the {reference} wildcard.
    Route::get('/references/export', [ReferenceController::class, 'export'])->name('references.export');
    Route::post('/references/import', [ReferenceController::class, 'import'])->name('references.import');
    Route::post('/references/doi', [ReferenceController::class, 'doiLookup'])->name('references.doi');

    Route::get('/references/{reference}', [ReferenceController::class, 'show'])->name('references.show');
    Route::get('/references/{reference}/edit', [ReferenceController::class, 'edit'])->name('references.edit');
    Route::put('/references/{reference}', [ReferenceController::class, 'update'])->name('references.update');
    Route::delete('/references/{reference}', [ReferenceController::class, 'destroy'])->name('references.destroy');

    // Profile (from Breeze). /dashboard is kept as an alias so the auth
    // redirects generated by Breeze keep working.
    Route::get('/dashboard', fn () => redirect()->route('references.index'))->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';
